name: Build

on:
  push:

jobs:

  find-changes:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.changes.outputs.build }}
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:

      - name: Deep checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find changes
        id: changes
        run: |
          matrix=$(git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.event.after }} | grep -E '^images/' | xargs -r -n1 -d'\n' dirname | sort -u | jq -R -s -c 'split("\n")|map(select(.|length>0))|{"include":map({"path":.})}')
          echo "::set-output name=matrix::$matrix"
          echo "::set-output name=build::$(jq '.include|length>0' <<<$matrix)"

  build:
    if: ${{ needs.find-changes.outputs.build == 'true' }}
    runs-on: ubuntu-latest
    needs: [ find-changes ]
    strategy:
      matrix: ${{ fromJSON(needs.find-changes.outputs.matrix) }}

    steps:
      - name: Get image name and tag
        id: image
        run: |
          ref=${{ github.ref }}
          ref=${ref#refs/heads/}
          echo "::set-output name=IMAGE::$(basename $(dirname ${{ matrix.path }}))"
          echo "::set-output name=TAG::$(basename ${{ matrix.path }})"
          echo "::set-output name=PATH::${{ matrix.path }}"
          echo "::set-output name=TAG_SUFFIX::$( [ "$ref" != "${{ github.repository.default_branch }}" ] && echo ".${ref//\//-}" || true)"
      
      - name: Shallow checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.image.outputs.PATH }}
          file: ${{ steps.image.outputs.PATH }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.image.outputs.IMAGE }}:${{ steps.image.outputs.TAG }}${{ steps.image.outputs.TAG_SUFFIX }}
